name: 'Build and deploy container for testing'

on: 
  push:
    branches:
      - master

jobs:
  deploy-container:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: azure/actions/login@master
      with:
        creds: ${{ secrets.AZURE_SP }}

    - uses: azure/container-actions/docker-login@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - run: |
        docker build . -t jasonfreeberg/jboss:${{ github.sha }} --build-arg RH_USERNAME --build-arg RH_PASSWORD
        docker push jasonfreeberg/jboss:${{ github.sha }}
      env:
        RH_USERNAME: ${{ secrets.RH_USERNAME }}
        RH_PASSWORD: ${{ secrets.RH_PASSWORD }}

    - uses: azure/appservice-actions/webapp-container@master
      with:
        app-name: 'freeberg-jboss'
        images: 'jasonfreeberg/jboss:${{ github.sha }}'
