name: 'Build and deploy container for testing'

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
  schedule:
    - cron: '0 8 * * *'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    # Checkout the Repo
    - uses: actions/checkout@v3

    # Login to docker hub build and publish
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - run: |
        docker build -t ${{ secrets.DOCKER_REPO }}:latest .
        docker push ${{ secrets.DOCKER_REPO }}:latest

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: [build-and-push]
  #   steps:
  #   # Login to Azure with CLI with Federated with Github
  #   - name: 'Az CLI Login via OIDC'
  #     uses: azure/login@v1.4.0
  #     with:
  #       client-id: ${{ secrets.AZURE_AD_CLIENT_ID }}
  #       tenant-id: ${{ secrets.AZURE_AD_TENANT_ID }}
  #       subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  #   - uses: azure/webapps-deploy@v2
  #     with:
  #       app-name: 'JavaEEOnJBossOn'
  #       images: ${{ secrets.DOCKER_REPO }}:${{ github.sha }}

  chatops:
      name: Send notifications with Teams
      needs: [build-and-push]
      runs-on: ubuntu-latest
      environment: ${{ inputs.ENVIRONMENT }}
      steps:
            # Send Chat Ops notification
        - name: Send chat ops notification to teams
          uses: dhollerbach/actions.send-message-to-ms-teams@1.0.10
          with:
            webhook: ${{ secrets.TEAMS_WEBHOOK }}
            message: 'Deployment Completed for commit: ${{ github.sha }} check logs to determine success.'