on:
  release:
    types:
      - published

jobs:
  publish-container:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: azure/container-actions/docker-login@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - run: |
        docker build . -t jasonfreeberg/jboss-on-app-service:${{ GITHUB_REF }}
        docker push jasonfreeberg/jboss-on-app-service:${{ GITHUB_REF }}